COMMAND_MODE, \
COMMAND_INPUT_MODE, \
INSERT_MODE, \
REPLACE_MODE, \
VISUAL_BLOCK_MODE, \
VISUAL_LINE_MODE, \
VISUAL_MODE,\
DELETE_MODE = list(range(8))

UP, DOWN, LEFT, RIGHT, HOME, END = list(range(6))

